fragment LandingPage on LandingPage {
    _metadata {
        ...PageUrl
        published
        displayName
    }
    TopContentArea {
        _metadata {
            types
        }
        ...ContentArea
    }
    MainContentArea {
        _metadata {
            types
        }
        ...ContentArea
    }
    SeoSettings {
        ...PageSeoSettingsProperty
    }
    PageAdminSettings {
        ...PageAdminSettingsProperty
    }
    PageSiteSettings {
        ... on SiteSettings {
            LogoResolution
            Logo {
                url { default }
                ... on _Image {
                    item: _metadata {
                        Url: url { default }
                        AltText: displayName
                    }
                }
            }
        }
    }
    PageSiteStyles {
        ... on SiteStyles {
            daisyuiTheme
            primary
            primaryContent
            secondary
            secondaryContent
            accent
            accentContent
            neutral
            neutralContent
            base100
            base200
            base300
            baseContent
            info
            infoContent
            success
            successContent
            warning
            warningContent
            error
            errorContent
            radiusSelector
            radiusField
            radiusBox
            sizeSelector
            sizeField
            borderWidth
            depth
            noise
            textXs
            textSm
            textBase
            textLg
            textXl
            text2xl
            text3xl
            text4xl
            text5xl
            text6xl
            text7xl
            text8xl
            text9xl
            freeFormStyles
            font
            cssFile {
                _metadata {
                    lastModified
                    url { default }
                }
            }
        }
    }
}
